package com.phcarvalho.model.corba.server;


/**
* com/phcarvalho/model/corba/server/_ServerServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public class _ServerServiceStub extends org.omg.CORBA.portable.ObjectImpl implements ServerService
{

  public void connectToServer (com.phcarvalho.model.corba.FileMetadata[] fileMetadataArray)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("connectToServer", true);
                com.phcarvalho.model.corba.FileMetadataArrayHelper.write ($out, fileMetadataArray);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                connectToServer (fileMetadataArray        );
            } finally {
                _releaseReply ($in);
            }
  } // connectToServer

  public com.phcarvalho.model.corba.FileMetadata[] search (String text)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("search", true);
                $out.write_string (text);
                $in = _invoke ($out);
                com.phcarvalho.model.corba.FileMetadata $result[] = com.phcarvalho.model.corba.FileMetadataArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return search (text        );
            } finally {
                _releaseReply ($in);
            }
  } // search

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/phcarvalho/model/corba/server/ServerService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServerServiceStub
