package com.phcarvalho.model.corba.server;


/**
* com/phcarvalho/model/corba/server/ServerServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

abstract public class ServerServiceHelper
{
  private static String  _id = "IDL:com/phcarvalho/model/corba/server/ServerService:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerServiceHelper.id (), "ServerService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerService)
      return (ServerService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ServerServiceStub stub = new _ServerServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerService)
      return (ServerService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ServerServiceStub stub = new _ServerServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
