package com.phcarvalho.model.corba.server;


/**
* com/phcarvalho/model/corba/server/ServerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public interface ServerServiceOperations 
{
  void connectToServer(com.phcarvalho.model.corba.FileMetadata[] fileMetadataArray);
  com.phcarvalho.model.corba.FileMetadata[] search(String text);
} // interface ServerServiceOperations
