package com.phcarvalho.model.corba.server;

/**
* com/phcarvalho/model/corba/server/ServerServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public final class ServerServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerService value = null;

  public ServerServiceHolder ()
  {
  }

  public ServerServiceHolder (ServerService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerServiceHelper.type ();
  }

}
