package com.phcarvalho.model.corba;


/**
* com/phcarvalho/model/corba/FileMetadataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

abstract public class FileMetadataHelper
{
  private static String  _id = "IDL:com/phcarvalho/model/corba/FileMetadata:1.0";

  public static void insert (org.omg.CORBA.Any a, FileMetadata that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileMetadata extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = com.phcarvalho.model.corba.UserHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "user",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FileMetadataHelper.id (), "FileMetadata", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileMetadata read (org.omg.CORBA.portable.InputStream istream)
  {
    FileMetadata value = new FileMetadata ();
    value.user = com.phcarvalho.model.corba.UserHelper.read (istream);
    value.name = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileMetadata value)
  {
    com.phcarvalho.model.corba.UserHelper.write (ostream, value.user);
    ostream.write_string (value.name);
  }

}
