package com.phcarvalho.model.corba;


/**
* com/phcarvalho/model/corba/FileMetadataArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public final class FileMetadataArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public FileMetadata value[] = null;

  public FileMetadataArrayHolder ()
  {
  }

  public FileMetadataArrayHolder (FileMetadata[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileMetadataArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileMetadataArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileMetadataArrayHelper.type ();
  }

}
