package com.phcarvalho.model.corba;


/**
* com/phcarvalho/model/corba/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  public User ()
  {
  } // ctor

  public User (String _id)
  {
    id = _id;
  } // ctor

} // class User
