package com.phcarvalho.model.corba.client;


/**
* com/phcarvalho/model/corba/client/ClientServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public interface ClientServiceOperations 
{
  com.phcarvalho.model.corba.FileData downloadFileData(com.phcarvalho.model.corba.FileMetadata fileMetadata);
} // interface ClientServiceOperations
