package com.phcarvalho.model.corba.client;

/**
* com/phcarvalho/model/corba/client/ClientServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Quarta-feira, 16 de Outubro de 2019 03h30min06s BRT
*/

public final class ClientServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientService value = null;

  public ClientServiceHolder ()
  {
  }

  public ClientServiceHolder (ClientService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientServiceHelper.type ();
  }

}
